src/AP.CopyFiles.targets, src/AnalysisPrograms/SQLitePCLRaw.provider.e_sqlite3.dll.config, tests/Acoustics.Test/Acoustics.Test.csproj, tests/Acoustics.Test/RuntimesTests.cs, tests/Acoustics.Test/TestHelpers/PathHelper.cs, tests/Acoustics.Test/packages.config
Fixes #165
Also updates the version of MSTest we are using.
@peichins can I get you to download the AppVeyor asset from the build and see if it works on your Mac/Mono instance? Thanks
=> Adds sqlite native code for MacOS

src/AnalysisPrograms/AnalyseLongRecordings/AnalyseLongRecordings.Arguments.cs
Minor fix to correct a typo:
"seed" -> "see"
Fix #188
=> Fixed typo in --help

src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGB.cs, tests/Acoustics.Test/AnalysisPrograms/AnalyzeLongRecordings/TestAnalyzeLongRecording.cs
Address Issue #198
No longer produce summary ribbons. They were an idea that did not prove to be useful.
=> Removes FC summary ribbons

src/Acoustics.Shared/Extensions/DoubleExtensions.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGB.cs, tests/Acoustics.Test/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGBTests.cs, tests/Acoustics.Test/TestHelpers/TestHelper.cs
Fix faulty logic when drawing LDFC colour matrices. However note that errors are shown in gray because this is a most unlikely colour in LDFC spectrograms.
Closes #154
=> DrawRgbColourMatrix now renders gray for cells with NaN values

src/AnalysisPrograms/Sandpit.cs, src/AudioAnalysisTools/Indices/IndexDisplay.cs, src/AudioAnalysisTools/Indices/IndexProperties.cs
Summary index tracks now easier to view when they are long. Size of image has not changed, just the background components.
Example attached
Fixes #212
=> Implements alternating background colors for summary indices image

src/AnalysisConfigFiles/IndexPropertiesConfig.yml, src/AnalysisPrograms/Sandpit.cs, src/AudioAnalysisTools/DSP/FrequencyScale.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGB.cs, tests/Acoustics.Test/AnalysisPrograms/AnalyzeLongRecordings/TestAnalyzeLongRecording.cs, tests/Acoustics.Test/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGBTests.cs
I have finished with issue #199. I combined the grey scale spectrograms into one image because it is most helpful to be able to compare them side by side. If spectrograms are too wide then they are joined vertically.
=> Adds rendering of ALL grayscale LD spectrograms to standard indices generation

src/AnalysisPrograms/ConcatenateIndexFiles.cs, src/AnalysisPrograms/Sandpit.cs, src/AudioAnalysisTools/Indices/GapsAndJoins.cs, src/AudioAnalysisTools/Indices/IndexDisplay.cs, src/AudioAnalysisTools/Indices/IndexMatrices.cs, src/AudioAnalysisTools/Indices/IndexProperties.cs, src/AudioAnalysisTools/Indices/SpectralIndicesToAndFromTable.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGB.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramStitching.cs, src/AudioAnalysisTools/LongDurationSpectrograms/SpectrogramConstants.cs, tests/Acoustics.Test/InfiniteTextStreamTests.cs
Issue #170 and Issue #212 should now both be fixed.
Concatenated LDFC spectrograms do not show file joins but Concatenated summary index images do show file joins. Have previously included image showing what file joins now look like.
=> Concat crashes issue #170

src/AnalysisPrograms/AudioCutter.cs, src/AnalysisPrograms/Production/Validation/InRangeAttribute.cs, tests/Acoustics.Test/AnalysisPrograms/AudioCutterTests.cs
Closes #223
Manually tested 2 hour segment cuts on `Y:\Tshering\WBH_Walaytar\WBH_2017\Ada Lake\Card1_20170201\ADA_20170201_000036.wav.`
=> Enhances audio cutter

src/Acoustics.Shared/AppConfigHelper.cs, src/Acoustics.Shared/app.config, src/AnalysisPrograms/AnalysisPrograms.csproj, src/AnalysisPrograms/CheckEnvironment.cs, src/AnalysisPrograms/MainEntry.cs, src/AnalysisPrograms/Production/Exceptions.cs, src/AnalysisPrograms/Production/MainEntryUtilities.cs, src/AnalysisPrograms/packages.config
It now delays execution of a few things in AppConfigHelper so we can do more checks before crashing.
Check environment actually checks the mono version now, and multiple errors could happen as well to make the check-fix routine easier.
Intended to help dx #225 
@Allcharles can you test the appveyor build on your install. I've made this fix so AP.exe can at least get started long enough to provide a better error (user needs better mono version).
=> Tried to improve check environment

src/AnalysisBase/AnalyzerConfig.cs, src/AnalysisConfigFiles/Towsey.Acoustic.yml, src/AnalysisPrograms/AcousticIndices.cs, src/AnalysisPrograms/Sandpit.cs, src/AudioAnalysisTools/Indices/IndexCalculateConfig.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramConfig.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGB.cs
This branch consists of three commits.
All tests passed after the third and last commit.
Now able to include LDFC spectrogram properties in the Analysis config file.
=> Issue #192 add ldfc properties to acoustic config

AudioAnalysis.sln.DotSettings, src/Acoustics.Tools/Audio/SoxAudioUtility.cs, tests/Acoustics.Test/Acoustics.Test.csproj, tests/Acoustics.Test/TestHelpers/LeakyFfmpegAudioUtility.cs, tests/Acoustics.Test/TestHelpers/LeakySoxAudioUtility.cs, tests/Acoustics.Test/Tools/MasterAudioUtilityTests.cs, tests/Acoustics.Test/Tools/SoxUtilityTests.cs
In some cultures, where a comma is used as the decimal separator. In those cases, when we format commands for SoX the numbers would be separated with commas and the command would be invalid.
The commit fixes that by ensuring we only use the invariant culture when formatting floating point types.
Fixes #242
=> Fixes culture formatting bug for SoX commands

NuGet.Config, src/Acoustics.Shared/Acoustics.Shared.csproj, src/Acoustics.Shared/app.config, src/Acoustics.Shared/packages.config, src/Acoustics.Tools/app.config, src/Acoustics.Unsafe/Acoustics.Unsafe.csproj, src/Acoustics.Unsafe/app.config, src/AnalysisBase/app.config, src/AnalysisPrograms/AnalyseLongRecordings/AnalyseLongRecording.cs, src/AnalysisPrograms/AnalysisPrograms.csproj, src/AnalysisPrograms/CheckEnvironment.cs, src/AnalysisPrograms/Draw/RibbonPlots/RibbonPlot.Entry.cs, src/AnalysisPrograms/MainEntry.cs, src/AnalysisPrograms/Production/Exceptions.cs, src/AnalysisPrograms/Production/MainEntryUtilities.cs, src/AnalysisPrograms/Recognizers/Base/MultiRecognizer.cs, src/AnalysisPrograms/Recognizers/Base/RecognizerEntry.cs, src/AnalysisPrograms/packages.config, src/AudioAnalysisTools/app.config, src/TowseyLibrary/app.config, tests/Acoustics.Test/Acoustics.Test.csproj, tests/Acoustics.Test/AnalysisPrograms/Draw/RibbonPlots/RibbonPlotTests.cs, tests/Acoustics.Test/TestHelpers/ImageAssert.cs, tests/Acoustics.Test/TestHelpers/TestImage.cs, tests/Acoustics.Test/packages.config
=> Fixes System.Numerics.Vectors not loading on some systems and produces better errors for reflection loading exceptions

src/AED/AED.fsproj, src/AED/packages.config, src/Acoustics.Shared.FSharp/Acoustics.Shared.FSharp.fsproj, src/Acoustics.Shared.FSharp/packages.config, src/AnalysisConfigFiles/RecognizerConfigFiles/Towsey.PteropusSpecies.yml, src/AnalysisPrograms/AnalysisPrograms.csproj, src/AnalysisPrograms/Recognizers/LitoriaFallax.cs, src/AnalysisPrograms/Recognizers/LitoriaFreycineti.cs, src/AnalysisPrograms/Recognizers/LitoriaRothii.cs, src/AnalysisPrograms/Recognizers/PteropusSpecies.cs, src/AnalysisPrograms/Recognizers/UperoleiaInundata.cs, src/AnalysisPrograms/Recognizers/UperoleiaMimula.cs, src/AnalysisPrograms/Sandpit.cs, src/AudioAnalysisTools/AcousticEvent.cs, src/AudioAnalysisTools/DSP/SNR.cs, src/AudioAnalysisTools/StandardSpectrograms/SpectrogramTools.cs, src/TowseyLibrary/PulseTrain.cs, src/TowseyLibrary/TowseyLibrary.csproj, tests/AED.Test/AED.Test.fsproj, tests/AED.Test/packages.config
=> Flying fox recognizer

src/AnalysisConfigFiles/IndexPropertiesConfig.yml, src/AnalysisConfigFiles/SpectrogramFalseColourConfig.yml, src/AnalysisConfigFiles/Towsey.Acoustic.yml, src/AnalysisPrograms/ConcatenateIndexFiles.cs, src/AnalysisPrograms/DrawLongDurationSpectrograms.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramConfig.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramDistance.cs, src/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGB.cs, tests/Acoustics.Test/AnalysisPrograms/Concatenation/ConcatenationTests.cs, tests/Acoustics.Test/AudioAnalysisTools/LongDurationSpectrograms/LDSpectrogramRGBTests.cs, tests/Acoustics.Test/TestHelpers/ImageAssert.cs
I have adjusted rendering of indices in blue ie CVR and EVN. I have also changed the colour correction for blue. This has broken unit tests involving ldfc spectrograms but can be easily fixed. Main issue is can you check the adjusted colours of ldfc spectrograms, especially the one which had insect track with a cyan halo around blue. 
Closes #274
=> Ldfc spectrogram color correction issue #274

.vscode/tasks.json, src/Acoustics.Shared/Extensions/ExtensionsGeneral.cs, src/Acoustics.Shared/Extensions/ProcessExtensions.cs, src/Acoustics.Shared/Extensions/SystemExtensions.cs, src/AnalysisPrograms/Production/MainEntryUtilities.cs, tests/Acoustics.Test/AnalysisPrograms/Production/MainEntryUtilitiesTests.cs, tests/Acoustics.Test/Shared/Extensions/ProcessExtensionsTests.cs, tests/Acoustics.Test/TestHelpers/Assertions.cs
Wrapped windows only software for retrieving parent process.
- Renamed `ExtensionsSystem.cs` to `ExtensionsGeneral.cs`
- Removed warnings from `ExtensionsGeneral.cs` file
- Extracted `ProcessExtensions` class to separate file
- Return null when non windows computer attempts to retrieve parent process
- Updated VSCode tasks
- May be possible to enable retrieval of parent process in future using .NET Core API: https://github.com/dotnet/runtime/issues/24423
=> Process extension

src/AnalysisConfigFiles/RecognizerConfigFiles/Towsey.AnthusNovaeseelandiae.yml, src/AnalysisConfigFiles/RecognizerConfigFiles/Towsey.BotaurusPoiciloptilus.yml, src/AnalysisConfigFiles/RecognizerConfigFiles/Towsey.CisticolaExilis.yml, src/AnalysisConfigFiles/RecognizerConfigFiles/Towsey.NinoxBoobook.yml, src/AnalysisPrograms/Recognizers/Birds/AnthusNovaeseelandiae.cs, src/AnalysisPrograms/Recognizers/Birds/BotaurusPoiciloptilus.cs, src/AnalysisPrograms/Recognizers/Birds/CisticolaExilis.cs, src/AnalysisPrograms/Recognizers/Birds/NinoxBoobook.cs, src/AnalysisPrograms/Recognizers/GenericRecognizer.cs, src/AudioAnalysisTools/Events/EventExtentions.cs, src/AudioAnalysisTools/Events/Types/CompositeEvent.cs, src/AudioAnalysisTools/Tracks/UpwardTrackAlgorithm.cs, src/TowseyLibrary/MatrixTools.cs, tests/Acoustics.Test/AnalysisPrograms/Recognizers/AustBitternTests.cs, tests/Acoustics.Test/AnalysisPrograms/Recognizers/AustralPipitTests.cs, tests/Acoustics.Test/AnalysisPrograms/Recognizers/CisticolaTests.cs, tests/Acoustics.Test/TowseyLibrary/MatrixToolsTests.cs, tests/Fixtures/Recordings/ms1_2559_630118_20170402_075841_30_0.wav
Issue #321
To merge latest four recognizers into master
All the four recognizers have the same general architecture and same structure to config.yml files
New functionality.
Have done some new unit tests
=> Alpha recognisers for pippit, bittern & cisticola

src/AnalysisConfigFiles/IndexPropertiesConfig.yml, src/AudioAnalysisTools/Indices/IndexCalculate.cs, src/AudioAnalysisTools/Indices/InitialiseIndexProperties.cs, src/AudioAnalysisTools/Indices/SummaryIndexValues.cs, src/AudioAnalysisTools/SpectralCentroid.cs, src/AudioAnalysisTools/StandardSpectrograms/AmplitudeSpectrogram.cs, src/TowseyLibrary/DataTools.cs, tests/Acoustics.Test/AudioAnalysisTools/Indices/IndexCalculateTest.cs, tests/Acoustics.Test/AudioAnalysisTools/SpectralCentroidTests.cs, tests/Acoustics.Test/Shared/CsvTests.cs
Issue #292 Spectral Centroid
What is the purpose of this PR?
To incorporate calculation of Spectral centroid as summary index into master.
Calculation of centroid and associated unit tests.
An additional track should be added into the image of the summary indices.
Closes #292
=> Issue292 spectral centroid

src/AnalysisConfigFiles/RecognizerConfigFiles/Towsey.NinoxBoobook.yml, src/AnalysisConfigFiles/RecognizerConfigFiles/Towsey.NinoxStrenua.yml, src/AnalysisPrograms/Recognizers/GenericRecognizer.cs, src/AudioAnalysisTools/Events/Types/EventPostProcessing.cs
Also changed name of parameter RemoveTemporallyEnclosedEvents to RemoveEnclosedEvents.
- Renamed RemoveTemporallyEnclosedEvents  to RemoveEnclosedEvents 
- And, actually returned post-processed events if RemoveEnclosedEvents  is `false` (rather than returning the raw results without any post-processing)
Any recogniser built on new setting will need to be adjusted
N/A
=> Fixed bug in when removing enclosed events

src/AudioAnalysisTools/Events/EventFilters.cs
See Issue #466 - Fix bug in EventFilters.cs
Shifted two lines of code to correct location i.e. after necessary checks have determined the list contains something to write.
-   [ ] Assign reviewers if you have permission
-   [ ] Assign labels if you have permission
-   [ ] Link issues related to PR
-   [ ] Link any PRs or issues blocking this PR from being merged
-   [ ] Remove/Reduce warnings from edited files
-   [X ] no unit tests affected.
=> Fix bug in EventFilters.cs

src/AP.VersionBuild.targets, src/Acoustics.Shared/ConfigFile/Config.cs, src/Acoustics.Shared/Extensions/ExtensionsString.cs, src/Acoustics.Shared/Extensions/FileInfoExtensions.cs, src/AnalysisBase/AnalyzerConfig.cs, src/AnalysisConfigFiles/.vscode/settings.json, src/AnalysisConfigFiles/RecognizerConfigFiles/QUT.MultiRecognizer.yml, src/AnalysisPrograms/AnalyseLongRecordings/AnalyseLongRecording.cs, src/AnalysisPrograms/Recognizers/Base/MultiRecognizer.cs, src/AssemblyMetadata.cs.template, src/git_version.ps1, tests/Acoustics.Test/AnalysisPrograms/Recognizers/MultiRecogniserTests.cs, tests/Acoustics.Test/TestHelpers/PathHelper.cs
The multirecogniser was not outputting any events after the component recognizers detected events.  The fix was simply to ensure NewEvents were aggregated as well as old style AcousticEvents.
Also:
- wrote tests for the multi recognizers
- ensured that multiple different ways of specifying sub-recognizers would work (name, soft-resolved config, absolute reference to files)
- also ensured configs were loaded before the main analysis starts - this should produce much nicer error messages and avoid cutting audio before telling the user about the inevitable failure.
- fixed the path to analysis programs in the test metdadata helper
Fixes #97
N/A
-   [x] Assign reviewers if you have permission
-   [x] Assign labels if you have permission
-   [x] Link issues related to PR
-   [x] Link any PRs …
=> Fixes bug in multi recogniser

src/AnalysisPrograms/Recognizers/Base/MultiRecognizer.cs, src/AnalysisPrograms/Recognizers/Base/RecognizerBase.cs, src/AnalysisPrograms/Recognizers/Frogs/LitoriaFallax.cs, src/AnalysisPrograms/Recognizers/Frogs/LitoriaFreycineti.cs, src/AnalysisPrograms/Recognizers/Frogs/LitoriaRothii.cs, src/AnalysisPrograms/Recognizers/GenericRecognizer.cs, src/AnalysisPrograms/Recognizers/PteropusSpecies.cs, src/AudioAnalysisTools/Events/Types/BlobEvent.cs, src/AudioAnalysisTools/Events/Types/OscillationEvent.cs, src/AudioAnalysisTools/Ocillations/Oscillations2012.cs, src/AudioAnalysisTools/Ocillations/Oscillations2019.cs, src/AudioAnalysisTools/StandardSpectrograms/SpectrogramTools.cs, src/TowseyLibrary/DataTools.cs, src/TowseyLibrary/ImageTools.cs, tests/Acoustics.Test/AnalysisPrograms/Recognizers/GenericRecognizerTests.cs, tests/Acoustics.Test/AnalysisPrograms/Recognizers/PteropusSpTests.cs, tests/Acoustics.Test/AudioAnalysisTools/StandardSpectrograms/SonogramTests.cs, tests/Acoustics.Test/TowseyLibrary/DataToolsTests.cs
Rescales plots before rendering them in generic recognisers. Fixes #469 
Wrote a unit test to demonstrate that the rescaling of plots is working.
None. Except that also change the FFT window to Hanning in MultiRecognizer.cs.
That may or maynot cause a change somewhere.
-   [Anthony ] Assign reviewers if you have permission
-   [ ] Assign labels if you have permission
-   [ ] Link issues related to PR
-   [ ] Link any PRs or issues blocking this PR from being merged
-   [ ] Remove/Reduce warnings from edited files
-   [ Yes] Unit tests have been added for changes
-   [ ] Ensure CI build is passing
=> Issue #469 rescaling of plot graphs

build/download_ap.ps1
- adds support to run the AP download script on ARM based mac
- add condition to check if build is mac and ARM based, use the macOS download version (ARM mac supports virtualisation)
- check /bin/test (location for test folder in mac)
- check is zsh shell is installed, and if so, add a path to both .zshrc and .profile
=> Updates to download_ap.ps1
